# Generated by Django 4.2.7 on 2023-11-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('incident', models.TextField()),
                ('name', models.CharField(max_length=120)),
            ],
        ),
    ]
