# Generated by Django 4.2.5 on 2023-11-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='Change',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='data',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='team',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
