# Generated by Django 4.2.5 on 2023-11-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0004_form_change_form_data_form_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='duration',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
